nelmio_api_doc:
    documentation:
        info:
            title: Symfony Skeleton
            description: Symfony Skeleton API doc
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Authorization: Bearer {jwt}'
                    name: Authorization
                    in: header
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
